[UI]
Language=eng
Theme=IBExpertDarkClassic
AllowIniOverrides=1

[FireBird]
InitialFBClientLib=/opt/FireBird/firebird6/lib/libfbclient.so.6.0.0

[Scripter]
EchoInput=0
StopOnFirstError=0
AutoDDL=0
IgnoreCreateDatabase=0
IgnoreGrants=0
ShowAffectedRows=0
ShowPerformanceStats=1

[Backup]
CloseDBBeforeBackup=1

[Restore]
DefaultPageSize=16384
DefaultNumBuffers=2048
DefaultSegmentSize=64
DefaultSegmentUnit=MB
RegisterDBAfterRestore=1

[ClipboardExport]
MaxExportRows=0

[MetaData]
AlwaysQuoteIdentifiers=1
CaseSensitiveObjectNames=1
ShowSystem=0

[IntelliSense]
ReloadCacheOnNodeExpand=0

[MetaDataTableExtract]
ExtractDomains=1
ExtractIndex=1
ExtractForeign=1
ExtractCheck=1
ExtractTrigger=1
ExtractGrant=1
ExtractData=0

[MainTreeView]
AlwaysRefresh=0
Color=clRed
FontName=Arial
FontStyle=
FontSize=13
FontColor=clWhite

[QueryWindow]
ShowNavigator=1
BackgroundColor=clSilver
FontName=DejaVu Sans Mono
FontSize=10
FontColor=clWhite
FontStyle=

[TransactionDefaults]
; Isolation Level:
; 0 = read_committed
; 1 = read_committed + rec_version
; 2 = concurrency
; 3 = consistency
Isolation=1
; Zugriff: ReadOnly / ReadWrite
ReadOnly=0
; Lock Verhalten: Wait / NoWait
Wait=1
; Record Version: rec_version / no_rec_version
RecVersion=1
; AutoCommit: true/false
AutoCommit=0
; Firebird 4+ Feature: ReadConsistency
ReadConsistency=0
; Lock Timeout in ms
LockTimeout=5000
; Optionaler Name / Label für die Transaction
TxName=DEFAULT_TRANSACTION
